name: eazy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Packages
  http: ^1.1.0
  dio: ^5.8.0+1
  provider: ^6.0.5
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  pinput: ^4.0.0
  share_plus: ^9.0.0
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  get_it: ^8.2.0
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  carousel_slider_plus: ^6.0.0
  smooth_page_indicator: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Eazy.png"
